//authedUser action types
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const LOGIN_AUTHED_USER = 'LOGIN_AUTHED_USER';
export const LOGOUT_AUTHED_USER = 'LOGOUT_AUTHED_USER';

//polls action types
export const RECEIVE_INITIAL_POLLS = 'RECEIVE_INITIAL_POLLS';
export const ADD_ANSWER_TO_POLL = 'ADD_ANSWER_TO_POLL';
export const UPDATE_USER_IN_POLL = 'UPDATE_USER_IN_POLL';
export const CREATE_NEW_POLL = 'CREATE_NEW_POLL';
export const REMOVE_VOTE_FROM_POLL = 'REMOVE_VOTE_FROM_POLL';
export const REMOVE_ALL_POLLS = 'REMOVE_ALL_POLLS';

//users action types
export const RECEIVE_INITIAL_USERS = 'RECEIVE_INITIAL_USERS';
export const ADD_ANSWER_TO_USER = 'ADD_ANSWER_TO_USER';
export const UPDATE_ANSWER_IN_USER = 'UPDATE_ANSWER_IN_USER';
export const ADD_QUESTION_TO_USER = 'ADD_QUESTION_TO_USER';
export const REMOVE_ANSWER_FROM_USER = 'REMOVE_ANSWER_FROM_USER';
export const REMOVE_ALL_USERS = 'REMOVE_ALL_USERS';

